// <auto-generated />
using System;
using HeYuanERP.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeYuanERP.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250909_InitialAuth")]
public partial class InitialAuth : Migration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("HeYuanERP.Domain.Entities.User", b =>
        {
            b.Property<string>("Id")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<bool>("Active")
                .HasColumnType("bit");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("CreatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("LoginId")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<string>("PasswordHash")
                .IsRequired()
                .HasMaxLength(512)
                .HasColumnType("nvarchar(512)");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.HasKey("Id");
            b.HasIndex("LoginId").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.Role", b =>
        {
            b.Property<string>("Id")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<bool>("Active")
                .HasColumnType("bit");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("CreatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("Roles");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.Permission", b =>
        {
            b.Property<string>("Id")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");

            b.Property<bool>("Active")
                .HasColumnType("bit");

            b.Property<string>("Code")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("CreatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.Property<string>("Description")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)");

            b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("datetime2");

            b.Property<string>("UpdatedBy")
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)");

            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("Permissions");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.UserRole", b =>
        {
            b.Property<string>("UserId")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");
            b.Property<string>("RoleId")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("UserRoles");
            b.HasOne("HeYuanERP.Domain.Entities.User", null)
                .WithMany("UserRoles")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade);
            b.HasOne("HeYuanERP.Domain.Entities.Role", null)
                .WithMany("UserRoles")
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.RolePermission", b =>
        {
            b.Property<string>("RoleId")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");
            b.Property<string>("PermissionId")
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2");

            b.HasKey("RoleId", "PermissionId");
            b.HasIndex("PermissionId");
            b.ToTable("RolePermissions");
            b.HasOne("HeYuanERP.Domain.Entities.Role", null)
                .WithMany("RolePermissions")
                .HasForeignKey("RoleId")
                .OnDelete(DeleteBehavior.Cascade);
            b.HasOne("HeYuanERP.Domain.Entities.Permission", null)
                .WithMany("RolePermissions")
                .HasForeignKey("PermissionId")
                .OnDelete(DeleteBehavior.Cascade);
        });
    }
}

