// <auto-generated />
using System;
using HeYuanERP.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeYuanERP.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
public partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        // Users
        modelBuilder.Entity("HeYuanERP.Domain.Entities.User", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<bool>("Active").HasColumnType("bit");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("LoginId").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(512).HasColumnType("nvarchar(512)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("LoginId").IsUnique();
            b.ToTable("Users");
        });

        // Roles
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Role", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<bool>("Active").HasColumnType("bit");
            b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("Roles");
        });

        // Permissions
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Permission", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<bool>("Active").HasColumnType("bit");
            b.Property<string>("Code").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("Permissions");
        });

        // UserRoles
        modelBuilder.Entity("HeYuanERP.Domain.Entities.UserRole", b =>
        {
            b.Property<string>("UserId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("RoleId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("UserRoles");
        });

        // RolePermissions
        modelBuilder.Entity("HeYuanERP.Domain.Entities.RolePermission", b =>
        {
            b.Property<string>("RoleId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("PermissionId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.HasKey("RoleId", "PermissionId");
            b.HasIndex("PermissionId");
            b.ToTable("RolePermissions");
        });

        // Accounts
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Account", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<bool>("Active").HasColumnType("bit");
            b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime?>("LastEventDate").HasColumnType("datetime2");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("OwnerId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("TaxNo").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.HasIndex("Name");
            b.ToTable("Accounts");
        });

        // Contacts
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Contact", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Email").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<bool>("IsPrimary").HasColumnType("bit");
            b.Property<string>("Mobile").HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Phone").HasMaxLength(30).HasColumnType("nvarchar(30)");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Title").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("AccountId");
            b.HasIndex("AccountId", "IsPrimary");
            b.ToTable("Contacts");
        });

        // Products
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Product", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<bool>("Active").HasColumnType("bit");
            b.Property<string>("Code").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<decimal?>("DefaultPrice").HasColumnType("decimal(18,2)");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Spec").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Unit").HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.HasIndex("Name");
            b.ToTable("Products");
        });

        // Attachments
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Attachment", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ContentType").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("FileName").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)");
            b.Property<long>("Size").HasColumnType("bigint");
            b.Property<string>("RefId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("RefType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Sha256").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("StorageUri").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
            b.Property<string>("UploadedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("RefType", "RefId");
            b.ToTable("Attachments");
        });

        // 客户共享（AccountShares）
        modelBuilder.Entity("HeYuanERP.Domain.Entities.AccountShare", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("TargetUserId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Permission").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime?>("ExpireAt").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("AccountId", "TargetUserId").IsUnique();
            b.ToTable("AccountShares");
        });

        // 客户拜访记录（AccountVisits）
        modelBuilder.Entity("HeYuanERP.Domain.Entities.AccountVisit", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ContactId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("VisitorId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("VisitDate").HasColumnType("datetime2");
            b.Property<string>("Subject").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Content").HasColumnType("nvarchar(max)");
            b.Property<string>("Location").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Result").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTime?>("NextActionAt").HasColumnType("datetime2");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("AccountId", "VisitDate");
            b.HasIndex("VisitorId", "VisitDate");
            b.HasIndex("AccountId");
            b.HasIndex("ContactId");
            b.HasIndex("VisitorId");
            b.ToTable("AccountVisits");
        });

        // ReportSnapshots
        modelBuilder.Entity("HeYuanERP.Domain.Entities.ReportSnapshot", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("FileUri").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Message").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ParamsJson").HasColumnType("nvarchar(max)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("FinishedAt").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("Name", "CreatedAt");
            b.ToTable("ReportSnapshots");
        });

        // SalesOrders
        modelBuilder.Entity("HeYuanERP.Domain.Entities.SalesOrder", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<DateTime>("OrderDate").HasColumnType("datetime2");
            b.Property<string>("OrderNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("OrderNo").IsUnique();
            b.HasIndex("AccountId", "OrderDate");
            b.ToTable("SalesOrders");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.SalesOrderLine", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("DeliveryDate").HasColumnType("datetime2");
            b.Property<decimal>("Discount").HasColumnType("decimal(9,6)");
            b.Property<string>("OrderId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<decimal>("TaxRate").HasColumnType("decimal(9,6)");
            b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("OrderId");
            b.HasIndex("ProductId");
            b.ToTable("SalesOrderLines");
        });

        // Deliveries
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Delivery", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("DeliveryNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("DeliveryDate").HasColumnType("datetime2");
            b.Property<string>("OrderId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("DeliveryNo").IsUnique();
            b.HasIndex("OrderId", "DeliveryDate");
            b.ToTable("Deliveries");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.DeliveryLine", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("DeliveryId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("OrderLineId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("DeliveryId");
            b.HasIndex("ProductId");
            b.HasIndex("OrderLineId");
            b.ToTable("DeliveryLines");
        });

        // Returns
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Return", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("OrderId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ReturnNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("ReturnDate").HasColumnType("datetime2");
            b.Property<string>("SourceDeliveryId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("ReturnNo").IsUnique();
            b.HasIndex("OrderId", "ReturnDate");
            b.ToTable("Returns");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.ReturnLine", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<string>("Reason").HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("ReturnId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("ReturnId");
            b.HasIndex("ProductId");
            b.ToTable("ReturnLines");
        });

        // PurchaseOrders
        modelBuilder.Entity("HeYuanERP.Domain.Entities.PurchaseOrder", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("PoNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("PoDate").HasColumnType("datetime2");
            b.Property<string>("VendorId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("PoNo").IsUnique();
            b.HasIndex("VendorId", "PoDate");
            b.ToTable("PurchaseOrders");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.POLine", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("PoId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<decimal>("UnitPrice").HasColumnType("decimal(18,2)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("PoId");
            b.HasIndex("ProductId");
            b.ToTable("POLines");
        });

        // POReceives
        modelBuilder.Entity("HeYuanERP.Domain.Entities.POReceive", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("PoId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("ReceiveDate").HasColumnType("datetime2");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("PoId", "ReceiveDate");
            b.ToTable("POReceives");
        });

        modelBuilder.Entity("HeYuanERP.Domain.Entities.POReceiveLine", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ReceiveId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<string>("Whse").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Loc").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("ReceiveId");
            b.HasIndex("ProductId");
            b.ToTable("POReceiveLines");
        });

        // InventoryBalances
        modelBuilder.Entity("HeYuanERP.Domain.Entities.InventoryBalance", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Loc").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<decimal>("Available").HasColumnType("decimal(18,4)");
            b.Property<decimal>("OnHand").HasColumnType("decimal(18,4)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Reserved").HasColumnType("decimal(18,4)");
            b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Whse").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("ProductId", "Whse", "Loc").IsUnique();
            b.HasIndex("ProductId");
            b.ToTable("InventoryBalances");
        });

        // InventoryTxns
        modelBuilder.Entity("HeYuanERP.Domain.Entities.InventoryTxn", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Loc").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<decimal>("Qty").HasColumnType("decimal(18,4)");
            b.Property<string>("ProductId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("RefId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("RefType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("TxnDate").HasColumnType("datetime2");
            b.Property<string>("TxnCode").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("Whse").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("ProductId", "TxnDate");
            b.HasIndex("TxnCode", "TxnDate");
            b.ToTable("InventoryTxns");
        });

        // Invoices
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Invoice", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
            b.Property<decimal>("AmountWithTax").HasColumnType("decimal(18,2)");
            b.Property<string>("DeliveryId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<DateTime>("InvoiceDate").HasColumnType("datetime2");
            b.Property<string>("InvoiceNo").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("OrderId").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<decimal>("TaxRate").HasColumnType("decimal(9,6)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("InvoiceNo").IsUnique();
            b.HasIndex("AccountId", "InvoiceDate");
            b.ToTable("Invoices");
        });

        // Payments
        modelBuilder.Entity("HeYuanERP.Domain.Entities.Payment", b =>
        {
            b.Property<string>("Id").HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<string>("AccountId").IsRequired().HasMaxLength(64).HasColumnType("nvarchar(64)");
            b.Property<decimal>("Amount").HasColumnType("decimal(18,2)");
            b.Property<string>("Currency").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)");
            b.Property<DateTime>("Date").HasColumnType("datetime2");
            b.Property<string>("Method").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<string>("RefNo").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Remark").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Status").HasMaxLength(20).HasColumnType("nvarchar(20)");
            b.Property<string>("VoucherNo").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
            b.Property<string>("CreatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
            b.Property<string>("UpdatedBy").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("AccountId", "Date");
            b.ToTable("Payments");
        });
    }
}
