using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HeYuanERP.Domain.Entities;

[Table("JournalEntries")]
public class JournalEntry
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string JournalNumber { get; set; } = string.Empty; // 凭证号

    [Required]
    [StringLength(50)]
    public string JournalType { get; set; } = string.Empty; // General, Adjustment, Reconciliation, Closing

    [StringLength(50)]
    public string Status { get; set; } = "Draft"; // Draft, Posted, Reversed

    public DateTime JournalDate { get; set; } = DateTime.UtcNow;

    public DateTime? PostingDate { get; set; } // 过账日期

    [Required]
    [StringLength(100)]
    public string Description { get; set; } = string.Empty; // 凭证摘要

    // 金额信息
    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalDebitAmount { get; set; } // 总借方金额

    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalCreditAmount { get; set; } // 总贷方金额

    [StringLength(10)]
    public string Currency { get; set; } = "CNY"; // 币种

    [Column(TypeName = "decimal(10,6)")]
    public decimal ExchangeRate { get; set; } = 1; // 汇率

    // 期间信息
    public int FiscalYear { get; set; } // 会计年度

    public int FiscalPeriod { get; set; } // 会计期间

    [StringLength(20)]
    public string PeriodName { get; set; } = string.Empty; // 期间名称

    // 来源信息
    [StringLength(50)]
    public string SourceType { get; set; } = string.Empty; // Manual, Reconciliation, Adjustment, System

    [StringLength(100)]
    public string SourceDocument { get; set; } = string.Empty; // 来源单据

    [StringLength(100)]
    public string SourceTransactionId { get; set; } = string.Empty; // 来源交易ID

    public int? SourceAdjustmentEntryId { get; set; } // 来源调整单ID

    [ForeignKey("SourceAdjustmentEntryId")]
    public virtual AdjustmentEntry? SourceAdjustmentEntry { get; set; }

    public int? SourceReconciliationId { get; set; } // 来源对账记录ID

    [ForeignKey("SourceReconciliationId")]
    public virtual ReconciliationRecord? SourceReconciliation { get; set; }

    // 处理人员
    [Required]
    public int PreparedByUserId { get; set; }

    [StringLength(100)]
    public string PreparedByUserName { get; set; } = string.Empty;

    public int? PostedByUserId { get; set; }

    [StringLength(100)]
    public string PostedByUserName { get; set; } = string.Empty;

    public DateTime? PostedAt { get; set; }

    // 审批信息
    public bool RequiresApproval { get; set; } = false;

    public int? ApprovedByUserId { get; set; }

    [StringLength(100)]
    public string ApprovedByUserName { get; set; } = string.Empty;

    public DateTime? ApprovedAt { get; set; }

    [StringLength(50)]
    public string ApprovalStatus { get; set; } = "Pending"; // Pending, Approved, Rejected

    [StringLength(1000)]
    public string ApprovalComments { get; set; } = string.Empty;

    // 撤销信息
    public bool IsReversed { get; set; } = false;

    public DateTime? ReversedDate { get; set; }

    public int? ReversedByUserId { get; set; }

    [StringLength(100)]
    public string ReversedByUserName { get; set; } = string.Empty;

    [StringLength(500)]
    public string ReversalReason { get; set; } = string.Empty;

    public int? ReversalJournalId { get; set; } // 撤销凭证ID

    [ForeignKey("ReversalJournalId")]
    public virtual JournalEntry? ReversalJournal { get; set; }

    // 业务分类
    [StringLength(100)]
    public string BusinessCategory { get; set; } = string.Empty; // Sales, Purchase, Inventory, Financial

    [StringLength(100)]
    public string BusinessSubCategory { get; set; } = string.Empty;

    [StringLength(100)]
    public string TransactionType { get; set; } = string.Empty; // Invoice, Payment, Adjustment, etc.

    // 关联业务单据
    [StringLength(100)]
    public string RelatedOrderNumber { get; set; } = string.Empty;

    [StringLength(100)]
    public string RelatedInvoiceNumber { get; set; } = string.Empty;

    [StringLength(100)]
    public string RelatedPaymentNumber { get; set; } = string.Empty;

    // 税务信息
    [Column(TypeName = "decimal(18,2)")]
    public decimal TotalTaxAmount { get; set; } // 总税额

    [StringLength(50)]
    public string TaxPeriod { get; set; } = string.Empty; // 税务期间

    public bool AffectsTaxReporting { get; set; } = false; // 影响税务申报

    // 合规和监管
    public bool IsRegulatoryRequired { get; set; } = false;

    [StringLength(100)]
    public string RegulatoryReference { get; set; } = string.Empty;

    public bool RequiresExternalReporting { get; set; } = false;

    [StringLength(500)]
    public string ComplianceNotes { get; set; } = string.Empty;

    // 自动化信息
    public bool IsAutoGenerated { get; set; } = false;

    [StringLength(100)]
    public string AutoGenerationRule { get; set; } = string.Empty;

    public bool IsRecurring { get; set; } = false;

    [StringLength(50)]
    public string RecurringFrequency { get; set; } = string.Empty;

    public DateTime? NextRecurringDate { get; set; }

    // 工作流
    [StringLength(50)]
    public string WorkflowStatus { get; set; } = string.Empty;

    [StringLength(2000)]
    public string WorkflowHistory { get; set; } = string.Empty; // JSON格式

    // 附件和文档
    [StringLength(1000)]
    public string AttachmentUrls { get; set; } = string.Empty; // JSON格式

    [StringLength(2000)]
    public string SupportingDocuments { get; set; } = string.Empty;

    // 审计跟踪
    [StringLength(2000)]
    public string AuditTrail { get; set; } = string.Empty; // JSON格式的审计跟踪

    [StringLength(500)]
    public string DataIntegrityHash { get; set; } = string.Empty; // 数据完整性哈希

    // 集成信息
    [StringLength(100)]
    public string ExternalSystemId { get; set; } = string.Empty; // 外部系统ID

    [StringLength(100)]
    public string ExternalSystemReference { get; set; } = string.Empty;

    public DateTime? LastSyncDate { get; set; } // 最后同步时间

    [StringLength(50)]
    public string SyncStatus { get; set; } = string.Empty; // Synced, Failed, Pending

    // 备注
    [StringLength(2000)]
    public string Notes { get; set; } = string.Empty;

    [StringLength(2000)]
    public string InternalNotes { get; set; } = string.Empty;

    // 时间戳
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; } = string.Empty;

    [StringLength(100)]
    public string? UpdatedBy { get; set; }

    // 关联实体
    public virtual ICollection<JournalEntryLine> JournalLines { get; set; } = new List<JournalEntryLine>();

    // 计算属性
    public bool IsBalanced => Math.Abs(TotalDebitAmount - TotalCreditAmount) < 0.01m;

    public bool IsPosted => Status == "Posted";

    public bool IsEditable => Status == "Draft" && !IsPosted;

    public bool CanBePosted => IsBalanced && !IsPosted && (ApprovalStatus == "Approved" || !RequiresApproval);

    public decimal NetAmount => TotalDebitAmount - TotalCreditAmount;

    public string StatusDescription => Status switch
    {
        "Draft" => "草稿",
        "Posted" => "已过账",
        "Reversed" => "已撤销",
        _ => "未知"
    };

    public int LinesCount => JournalLines?.Count ?? 0;

    public bool HasTaxEntries => TotalTaxAmount > 0;

    public int DaysInDraft => IsPosted ? 0 : (int)(DateTime.UtcNow - CreatedAt).TotalDays;

    public bool IsOverdueForPosting => Status == "Draft" && DaysInDraft > 3; // 可配置
}

[Table("JournalEntryLines")]
public class JournalEntryLine
{
    [Key]
    public int Id { get; set; }

    [Required]
    public int JournalEntryId { get; set; }

    [ForeignKey("JournalEntryId")]
    public virtual JournalEntry JournalEntry { get; set; } = null!;

    public int LineNumber { get; set; } // 行号

    [Required]
    [StringLength(50)]
    public string AccountCode { get; set; } = string.Empty; // 科目代码

    [Required]
    [StringLength(200)]
    public string AccountName { get; set; } = string.Empty; // 科目名称

    [StringLength(50)]
    public string AccountType { get; set; } = string.Empty; // Asset, Liability, Equity, Revenue, Expense

    [StringLength(100)]
    public string AccountCategory { get; set; } = string.Empty; // 科目类别

    [Column(TypeName = "decimal(18,2)")]
    public decimal DebitAmount { get; set; } // 借方金额

    [Column(TypeName = "decimal(18,2)")]
    public decimal CreditAmount { get; set; } // 贷方金额

    [Required]
    [StringLength(200)]
    public string Description { get; set; } = string.Empty; // 摘要

    // 辅助核算
    [StringLength(100)]
    public string CostCenter { get; set; } = string.Empty; // 成本中心

    [StringLength(100)]
    public string Department { get; set; } = string.Empty; // 部门

    [StringLength(100)]
    public string Project { get; set; } = string.Empty; // 项目

    [StringLength(100)]
    public string BusinessUnit { get; set; } = string.Empty; // 业务单元

    [StringLength(100)]
    public string CustomerVendorCode { get; set; } = string.Empty; // 客户/供应商代码

    [StringLength(200)]
    public string CustomerVendorName { get; set; } = string.Empty; // 客户/供应商名称

    [StringLength(100)]
    public string ProductCode { get; set; } = string.Empty; // 产品代码

    [StringLength(200)]
    public string ProductName { get; set; } = string.Empty; // 产品名称

    // 数量和单价信息
    [Column(TypeName = "decimal(10,2)")]
    public decimal Quantity { get; set; }

    [StringLength(50)]
    public string Unit { get; set; } = string.Empty;

    [Column(TypeName = "decimal(18,6)")]
    public decimal UnitPrice { get; set; }

    // 外币信息
    [StringLength(10)]
    public string Currency { get; set; } = "CNY";

    [Column(TypeName = "decimal(10,6)")]
    public decimal ExchangeRate { get; set; } = 1;

    [Column(TypeName = "decimal(18,2)")]
    public decimal ForeignDebitAmount { get; set; } // 外币借方金额

    [Column(TypeName = "decimal(18,2)")]
    public decimal ForeignCreditAmount { get; set; } // 外币贷方金额

    // 税务信息
    [Column(TypeName = "decimal(5,2)")]
    public decimal TaxRate { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal TaxAmount { get; set; }

    [StringLength(50)]
    public string TaxCode { get; set; } = string.Empty;

    [StringLength(100)]
    public string TaxType { get; set; } = string.Empty; // VAT, Sales, Income, etc.

    // 业务标识
    [StringLength(100)]
    public string BusinessTransactionId { get; set; } = string.Empty;

    [StringLength(100)]
    public string SourceDocumentNumber { get; set; } = string.Empty;

    [StringLength(50)]
    public string SourceDocumentType { get; set; } = string.Empty;

    // 分析维度
    [StringLength(100)]
    public string AnalysisDimension1 { get; set; } = string.Empty;

    [StringLength(100)]
    public string AnalysisDimension2 { get; set; } = string.Empty;

    [StringLength(100)]
    public string AnalysisDimension3 { get; set; } = string.Empty;

    [StringLength(2000)]
    public string ExtendedAttributes { get; set; } = string.Empty; // JSON格式的扩展属性

    // 备注
    [StringLength(500)]
    public string LineNotes { get; set; } = string.Empty;

    // 计算属性
    public decimal NetAmount => DebitAmount - CreditAmount;

    public decimal AbsoluteAmount => Math.Abs(NetAmount);

    public bool IsDebit => DebitAmount > 0;

    public bool IsCredit => CreditAmount > 0;

    public decimal TotalAmountIncludingTax => AbsoluteAmount + TaxAmount;

    public decimal ForeignNetAmount => ForeignDebitAmount - ForeignCreditAmount;

    public bool HasForeignCurrency => Currency != "CNY";

    public bool HasTax => TaxAmount > 0;

    public bool HasQuantity => Quantity > 0;
}